### ISSUE TITLE
Api calls return 401 unauthorized using Service Worker in Firefox in production environment

### ISSUE THREAD

**Issue by ampratt** [AxaFrance/oidc-client#1131] opened 2023-08-23 06:54 UTC
### Issue and Steps to Reproduce

I have a React application. I have recently switched to using Service Worker mode. Chrome and Edge work as expected but when using Firefox, the api calls that require authorization return 401 unauthorized.

When running in development mode, or running a production build on my local machine, Firefox still works fine. But when deployed to production these errors show up in Firefox only.

My Firefox is a clean install with no added extensions.

I have the trusted domains file configured.

request Headers look to be identical between Chrome and Firefox. As it is using ServiceWorker mode I cannot actually see the auth bearer token being added to the request since it is handled by the service worker.

Localstorage and SessionStorage looks identical between Chrome and Firefox.

Is this somehow from the ServiceWorker?

### Versions
"@axa-fr/react-oidc": "7.3.1"

### Screenshots
401 from Firefox
![image](https://github.com/AxaFrance/oidc-client/assets/6746269/e887aa74-f4f4-42cb-9620-3549887a6978)

200 from Chrome
![image](https://github.com/AxaFrance/oidc-client/assets/6746269/caaba34c-3303-4d47-9469-da08ff3d9220)

#### Expected
able to make api calls to secure backend by passing auth bearer token with service worker.

#### Actual
receiving 401

**Comment by guillaume-chervet** [comment] 2023-08-23 12:31
Hi @ampratt ,  thank you for your issue. We removed a kind of hack code recently, does it work with a previous version? (I will tell you a version  in my next response).
What does look like your urls in dev mode?

Do you have network screens from service worker?

**Comment by guillaume-chervet** [comment] 2023-08-23 12:52
6.24.1 was the version before the hack removed.

**Comment by ampratt** [comment] 2023-08-23 13:24
thanks for checking @guillaume-chervet . i am on version 7.3.1. i upgraded 1 week ago from 6.16.1 when i also started to use ServiceWorker mode.

I can try downgrading to 6.24.1 and send some screenshots as well

**Comment by guillaume-chervet** [comment] 2023-08-23 13:41
I do not have any problem with firefox with the demo https://black-rock-0dc6b0d03.1.azurestaticapps.net/profile
Do you encouter any problem on it?

**Comment by ampratt** [comment] 2023-08-24 08:34
@guillaume-chervet the demo works ok in Firefox for me. But in my app I am able to log in and get the user from your library.
I am not able to call my own api, and the demo app does not have any custom api calling happening it seems.

I will try now today downgrading the version and test.

**Comment by ampratt** [comment] 2023-08-24 11:04
still have the same 401

the only network calls i see in Firefox are
![image](https://github.com/AxaFrance/oidc-client/assets/6746269/bb283045-1952-419a-90ed-d43a51aa9912)

while in Chrome I see this (the redirect is my backend) and in the second call from the service worker i see the actial bearer token injected
![image](https://github.com/AxaFrance/oidc-client/assets/6746269/b0b9a3e6-ecd7-4171-81f0-7df0e74718d7)

**Comment by guillaume-chervet** [comment] 2023-08-24 12:17
Hi @ampratt , thank you for the feedback.

If you refresh the page on firefox does it work? That strange why does it works on the demo and not your app.
It must have a reason. Do you have a sample of code that can reproduce the error?

**Comment by ampratt** [comment] 2023-08-24 12:47
page refresh doesn't help.

byt opening Firefox' Browser console I see these error logs which says something about terminating the service worker
![image](https://github.com/AxaFrance/oidc-client/assets/6746269/6237ed3e-c993-4fd9-8118-6b2a31d5b7b3)

although i see the service worker running in Firefox tab
![image](https://github.com/AxaFrance/oidc-client/assets/6746269/1b0cec5d-cadf-4616-b337-a677af8e668f)

**Comment by guillaume-chervet** [comment] 2023-08-24 12:56
Thank you @ampratt , the message is very interesting.
I will make some research about it!

**Comment by guillaume-chervet** [comment] 2023-08-25 10:49
I have tried a fix in version 7.3.4-alpha.1030
I cannot reproduce the problem, i have supressed unusefull waituntil.

**Comment by guillaume-chervet** [comment] 2023-09-05 13:49
hi @ampratt , did you test latest version on firefox?
I cannot reproduce it.

**Comment by ampratt** [comment] 2023-09-06 05:20
hi @guillaume-chervet . my family was moving last week so i have been away alot.
i will try the latest fix now today, thank you!

**Comment by ampratt** [comment] 2023-09-06 08:56
@guillaume-chervet the fix removed the error from happening about terminating the service worker.
and i still see the service worker running
![image](https://github.com/AxaFrance/oidc-client/assets/6746269/e64db42c-38a8-475b-a25e-e9d9691a7167)

but I still get the same 401 error 

![image](https://github.com/AxaFrance/oidc-client/assets/6746269/c11f845d-c2c3-40cd-ae8b-b74c6301bee7)

**Comment by ampratt** [comment] 2023-09-06 10:02
found one difference now.
in Chrome I see these cookies:
![image](https://github.com/AxaFrance/oidc-client/assets/6746269/b5a442db-17e9-4383-8d80-57988b584cea)

but in firefox the cookies are empty.

Could they be being blocked by default or something similar?

**Comment by ampratt** [comment] 2023-09-06 11:13
when working properly in other browsers, these cookies are set immediately when this call succeeds, before leaving keycloak login page
![image](https://github.com/AxaFrance/oidc-client/assets/6746269/48265e6d-0557-42ac-8d49-0c2d3e88e334)


![image](https://github.com/AxaFrance/oidc-client/assets/6746269/999c7724-146e-4dd6-89c5-e7f5fae123d4)

**Comment by guillaume-chervet** [comment] 2023-09-06 12:17
Thank you for your feedback @ampratt 

Cookies are not necessary for userinfo endpoint. Thied party cookie are blocked on firefox and safari when oidc server and client does not share same domain. 


Do you have the Header information about the request on firefox?

![image](https://github.com/AxaFrance/oidc-client/assets/52236059/0c787960-3e8e-474a-b4a5-35ae826cd155)

Service worker seem to work well now. We need to find out why your still have 401.

**Comment by ampratt** [comment] 2023-09-06 12:29
it is not the userinfo endpoint I am calling, it is my own backend which fetches custom data for our app.

the request and headers are here (same as in the original issue post)
![image](https://github.com/AxaFrance/oidc-client/assets/6746269/e3633f5b-8147-439b-b5d8-48d784d05a1b)

...

> Thied party cookie are blocked on firefox and safari when oidc server and client does not share same domain.

is there a standard workaround to this?

**Comment by guillaume-chervet** [comment] 2023-09-07 13:49
Yes, you can act on cookie configuration on server OIDC side or you may set up your OIDC server inside same domain than your app.

**Comment by ampratt** [comment] 2023-09-13 08:30
i think the issue is resolved now in that we have finally found the main root of the error. It is not actually with the cookies.
Firefox has a default policy in place that strips auth headers in redirects (and our failing endpoint is redirected on our backend)

setting these config options in Firefox locally allowed the requests to work as expected.

```
network.fetch.redirect.stripAuthHeader = false
network.http.redirect.stripAuthHeader = false
```

We only then need to find the proper solution to handle our redirects or rewrite in a way that Firefox will not strip the headers.

Thank you for your help!

**Comment by guillaume-chervet** [comment] 2023-09-13 09:19
hi  @ampratt , thank you very much for your feedback.
Good new and good job,
this seems hard to find out.

**Comment by guillaume-chervet** [comment] 2023-09-13 10:20
May we close the issue @ampratt ?

**Closed** 2023-09-14 19:48 UTC
