### ISSUE TITLE
vanilla-demo only (ok in react): won't listen to events from CheckSessionIFrame

### ISSUE THREAD

**Issue by ludojmj** [AxaFrance/oidc-client#957] opened 2023-02-08 18:30 UTC
### Issue and Steps to Reproduce

It seems that there's a regression affecting only vanillaJs.
When testing vanilla-demo, CheckSessionIFrame doesn't seem to send logout event in V6.14.2 as it used to in V6.12.1.
(I need to use pure vanillaJs instead of react).

Here is what I've checked:

---

1) Browsing localhost on two tabs
- Tab_1 http://localhost:4200
- Tab_2 http://localhost:4200
- Press logout button on Tab_2

react ==> **OK**
"You are now logged out" says demo.duendesoftware.com on Tab_2.
"Session timed out" says localhost:4200 on Tab_1.

vanilla-demo ==> **OK**
"You are now logged out" says demo.duendesoftware.com on Tab_2.
After refreshing, there's only the login button on Tab_1.

---

2) Browsing localhost on one tab and duendesoftware on another tab
- Tab_1 http://localhost:4200
- Tab_2 https://demo.duendesoftware.com
- Logout on Tab_2

react ==> **OK**
"You are now logged out" says demo.duendesoftware.com on Tab_2
"Session timed out" says localhost:4200 on Tab_2 (despite an error in console log saying: "TypeError: tokenResponse.data is undefined" - login.ts:165)

vanilla-demo ==> **NOT OK**
Nothing happens in vanilla (even if refreshing).
The token still works (I've checked with an API protected by duendesoftware and the token is still accepted).

### Versions

V6.14.2

#### Expected

Revoke token in vanilla-demo as in react demo when logging out from demo.duendesoftware.com.

#### Actual

The token is still valid in vanilla-demo (but revoked it on react demo) when logging out from demo.duendesoftware.com. 

### Additional Details

My conf in both react demo and vanilla-demo:
```
export const configuration = {
  client_id: "interactive.public.short",
  redirect_uri: window.location.origin + "/authentication/callback",
  silent_redirect_uri: window.location.origin + "/authentication/silent-callback",
  scope: "openid profile email api offline_access",
  authority: "https://demo.duendesoftware.com",
  service_worker_relative_url: "/OidcServiceWorker.js",
  service_worker_only: true,
  monitor_session: true
};
```

**Comment by guillaume-chervet** [comment] 2023-02-08 20:52
Thank you @ludojmj again for you issue, I will test it tomorrow.  This is strange because the code vanilla is identical to the react one.

**Comment by ludojmj** [comment] 2023-02-09 08:59
I agree.
So I don't understand why the behaviour is not the same with vanilla-demo.

With vanilla-demo, there's nothing like the following lines when disconnecting from duendesoftware:
```
CheckSessionIFrame: changed message from check session op iframe checkSessionIFrame.ts:57
CheckSessionIFrame.stop checkSessionIFrame.ts:78
```

Full console log pasted below (tested with Firefox in private mode);

**REACT**
```
Ouverture de http://localhost:4200/
Ouverture de https://demo.duendesoftware.com/connect/authorize?client_id=interactive.public.short&redirect_uri=http%3A%2F%2Flocalhost%3A4200%2Fauthentication%2Fcallback&scope=openid%20profile%20email%20api%20offline_access&response_type=code&youhou_demo=youhou&state=L5SdXIaa4H2Z8vyc&nonce=lvRd58NG0yeF&code_challenge=S4FPmlaFz4CMboCIOWGXNnn4KphagmHvOc1nj8fAxNs&code_challenge_method=S256
S4FPmlaFz4CMboCIOWGXNnn4KphagmHvOc1nj8fAxNs= bundle.js:4341:11
Ouverture de https://demo.duendesoftware.com/Account/Login
Download the React DevTools for a better development experience: https://reactjs.org/link/react-devtools react-dom.development.js:29840
CheckSessionIFrame.start :KP_hRjXNNBYkAdBBgbvY2ef_0HqFmUyPnCiAhPLFlkA.05074B7648BD1BE65C058B2E8DD43792 checkSessionIFrame.ts:67
CheckSessionIFrame: unchanged message from check session op iframe checkSessionIFrame.ts:61
CheckSessionIFrame: unchanged message from check session op iframe 2 checkSessionIFrame.ts:61
message { target: Window, isTrusted: true, data: "changed", origin: "https://demo.duendesoftware.com", lastEventId: "", source: {…}, ports: Restricted, srcElement: Window, currentTarget: Window, eventPhase: 2, … }
checkSessionIFrame.ts:56
CheckSessionIFrame: changed message from check session op iframe checkSessionIFrame.ts:57
CheckSessionIFrame.stop checkSessionIFrame.ts:78
zyKfZS9fyiJlUZbRqSw9hNmjOXHRj+3e3ax8vVPOSrg= crypto.ts:18
XHRPOSThttps://demo.duendesoftware.com/connect/token
[HTTP/1.1 400 Bad Request 133ms]

TypeError: tokenResponse.data is undefined
    loginCallbackAsync login.ts:141
    loginCallbackLocalAsync oidc.ts:314
    loginCallbackAsync oidc.ts:328
    silentLoginCallbackAsync oidc.ts:162
    silentLoginCallbackAsync vanillaOidc.ts:49
    playCallbackAsync SilentCallback.component.tsx:10
    SilentCallbackManager SilentCallback.component.tsx:12
    React 8
    workLoop scheduler.development.js:266
    flushWork scheduler.development.js:239
    performWorkUntilDeadline scheduler.development.js:533
    js scheduler.development.js:571
    js scheduler.development.js:633
    factory react refresh:6
    Webpack 24
login.ts:165
SessionMonitor._callback: Silent login failed, logging out other tabs: Error: oidc_login_required
    onmessage silentLogin.ts:76
    _silentLoginAsync silentLogin.ts:56
   [...]
checkSession.ts:36
```
​

**VANILLA DEMO**
```
Ouverture de http://localhost:4200/
http://localhost:4200/ index.tsx:20
Ouverture de https://demo.duendesoftware.com/connect/authorize?client_id=interactive.public.short&redirect_uri=http%3A%2F%2Flocalhost%3A4200%2F%23%2Fauthentication%2Fcallback&scope=openid%20profile%20email%20api%20offline_access&response_type=code&youhou_demo=youhou&state=jzZD6micOxbaJcNn&nonce=EvAqBEVHtEhB&code_challenge=V2_kkqz5qrkolJ7I93mI5DJcqVBxvsV21I1ZtVwX7kc&code_challenge_method=S256
V2/kkqz5qrkolJ7I93mI5DJcqVBxvsV21I1ZtVwX7kc= bundle.js:388:11
Ouverture de https://demo.duendesoftware.com/Account/Login
http://localhost:4200/#/authentication/callback?code=5A41E20…7DBB89AA7893DD0575&iss=https%3A%2F%2Fdemo.duendesoftware.com index.tsx:20
Ouverture de http://localhost:4200/
CheckSessionIFrame.start :nEqjJ97HGexZLfXdCU7GIEWaLhCUXMNg8Qt-Q80zCR0.4DE2376EFE6BCE7DBB89AA7893DD0575 bundle.js:314:9
CheckSessionIFrame: unchanged message from check session op iframe bundle.js:309:13
http://localhost:4200/ index.tsx:20
Ouverture de http://localhost:4200/
http://localhost:4200/ index.tsx:20
```

**Comment by guillaume-chervet** [comment] 2023-02-09 14:38
I can reproduce it @ludojmj , it is very strange :]

**Comment by guillaume-chervet** [comment] 2023-03-01 07:50
I took time but i found.
The vannilla demo was full refreshing the page. I set the demo router as single page Application.
https://github.com/AxaGuilDEv/react-oidc/commit/e34234a0bf9abd9bea87ce41cde8b4d36fc2a85b

There is still a bug because a full page refresh should rerun the checkSession Iframe successfully.

**Comment by guillaume-chervet** [comment] 2023-08-28 10:05
Hi @ludojmj , Thank you for your issue and all your feedbacks.
I close it but feel free to reopen it if needed :)

**Closed by guillaume-chervet** 2023-08-28 10:05 UTC
