### ISSUE TITLE
Blurring in the documentation

### ISSUE THREAD

**Issue by johnmeunier** [AxaFrance/oidc-client#446] opened 2020-05-12 08:39 UTC
Some useful stuffs are missing (or is not explicit) from the documentation : 

- For test with identityserver, there is some better configuration : 
  -   response_type: 'code',
  -   client_id: 'interactive.public',
- For Chrome with blocked third parties cookie, you have to add the authority in authorized cookies to prevent "Authentification en cours" stuck
- The "How to consume part" is not clear, OidcSecure or withOidcSecure are not just for HOC Method but are useful when you want to secure any part of your application. I think you can't use the useReactOidc without any consumer.
- oidc-client has to be install in your project independently. It's not clear when you install react-oidc. You have to deal with the npm error of oidc-client. 

I think, that's all the problem I encountered during the setup of my project.

**Comment by guillaume-chervet** [comment] 2023-08-28 10:14
Hi @johnmeunier , thank you very much for your issue.
I think the issue is not relevant for version 7.
Very sorry for the delay. I close the issue but feel free to reopen it if you need it.

**Closed by guillaume-chervet** 2023-08-28 10:14 UTC
Labels: enhancement, good first issue
